### ISSUE TITLE
endpoint in api that can be queried with valid study key for list of participant ids

### ISSUE THREAD

**Issue by smeddinck** [MORE-Platform/more-data-gateway#111]
return participant ids together with status information …

this makes adding the right participant ids to data records coming in through API as external observations much easier from the POV of external app / system devs

**Comment by andresgruber** [comment]
The endpoint needs to provide:

- Participant ID (no requirement to hash the data)
- Alias
- Status information

Information: Sending external data is bound to as specific observation, defined for the group using the external data!

**Comment by drtyyj** [comment]
Question: Should Participants without a studygroup be shown for all observations, no matter what studygroup the observation is for?

**Comment by andresgruber** [comment]
Additional requirement:

1. Adding **study group (id and name, if available)** and **date of enrollment** of the participant

**Comment by alireza-dhp** [comment]
In the current version, this endpoint can be called **regardless** of study status and the corresponding observation start and end dates!
We (Daniela and Alireza) agreed that this feature satisfied our current requirements.
